version: '3.1'
services:
  db:
    image: xploiterd/authking_db:latest
    networks:
      - app-network

  php:
    image: xploiterd/authking:latest
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root1
      DB_PASSWORD: newpassword
      DB_NAME: company
    networks:
      - app-network

networks:
  app-network:
